version: '3'
services:
  app:
    container_name: question_compose
    restart: always
    build: .
    ports:
      - 2024:2024
    volumes:
      - ./src:/home/node/app/src
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: app_mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/mongo:/data/db
