const swaggerJSDoc = require('swagger-jsdoc');

// Swagger definition
const swaggerDefinition = {
  openapi: '3.0.0', // Specification (optional, defaults to swagger: '2.0')
  info: {
    title: 'Express API with Swagger',
    version: '1.0.0',
    description: 'Documentation automatically generated by Swagger JSDoc',
  },
  servers: [
    {
      url: 'http://localhost:2024', // Replace with your server URL
      description: 'Development server',
    },
  ],
};

// Options for the swagger-jsdoc
const options = {
  swaggerDefinition,
  // Path to the API docs
  apis: ['./src/controllers/v1/admin/questionSet/routes.js','./src/controllers/v1/admin/seminar/routes.js'],  // Path to your API routes
};

// Initialize swagger-jsdoc
const swaggerSpec = swaggerJSDoc(options);

module.exports = swaggerSpec;
